stages:
  - build
  - codescan
  - artifactpublish

include:
  - local: '/pipeline_templates/import.yml'
  
build:
  stage: build
  extends: .build
  
code_scan:
  stage: codescan
  extends: .code_scan
  
publish:
  stage: artifactpublish
  variables:
    PACKAGE_TYPE: 'zip'
  needs:
    - job: compile_commit
      artifacts: true
  extends: .publish
